name: workforce_windows_client
description: Employee attendance desktop client for Windows.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_inactive_timer: ^1.1.3
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  camera: ^0.11.0+2
  camera_windows: ^0.2.2
  device_info_plus: ^10.1.2
  package_info_plus: ^8.1.2

  # ML
  onnxruntime: ^1.4.1
  ffi: ^2.1.0

  image: ^4.8.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/